DB_TYPE: postgresql
DB_HOST: localhost
DB_PORT: 5432
DB_USER: rbac
DB_PASSWD: rbac123
DB_NAME: rbac
DB_CONNECT_RETRY: 5
DB_CONNECT_TIMEOUT: 2000
HTTP_PORT: 3030
RETRY: 5
TIMEOUT: 2000

CACHE_TYPE: redis
CACHE_HOST: localhost
CACHE_PORT: 6380
CACHE_USER: lingj
CACHE_PASSWD: lingj123

JWT_SECRET_KEY: abc
JWT_EXPIRATION: 36000000

ALLOW_USER_SIGNUP: true
ALLOW_USER_CREATE_TENANT: true
